-- CreateEnum
CREATE TYPE "UserRole" AS ENUM ('ADMIN', 'MEMBER');

-- CreateEnum
CREATE TYPE "UserStatus" AS ENUM ('ACTIVE', 'SUSPENDED', 'DELETED');

-- CreateTable
CREATE TABLE "municipalities" (
    "code" CHAR(5) NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "province" VARCHAR(30) NOT NULL,

    CONSTRAINT "municipalities_pkey" PRIMARY KEY ("code")
);

-- CreateTable
CREATE TABLE "schools" (
    "id" UUID NOT NULL,
    "name" VARCHAR(150) NOT NULL,
    "normalized_name" VARCHAR(150) NOT NULL,
    "municipality_code" CHAR(5) NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "schools_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "users" (
    "id" UUID NOT NULL,
    "school_id" UUID NOT NULL,
    "email" VARCHAR(320) NOT NULL,
    "password_hash" VARCHAR(60) NOT NULL,
    "first_name" VARCHAR(100) NOT NULL,
    "last_name" VARCHAR(100) NOT NULL,
    "role" "UserRole" NOT NULL,
    "status" "UserStatus" NOT NULL DEFAULT 'ACTIVE',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "municipalities_name_idx" ON "municipalities"("name");

-- CreateIndex
CREATE UNIQUE INDEX "schools_normalized_name_municipality_code_key" ON "schools"("normalized_name", "municipality_code");

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- CreateIndex
CREATE INDEX "users_school_id_idx" ON "users"("school_id");

-- AddForeignKey
ALTER TABLE "schools" ADD CONSTRAINT "schools_municipality_code_fkey" FOREIGN KEY ("municipality_code") REFERENCES "municipalities"("code") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "users" ADD CONSTRAINT "users_school_id_fkey" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- LoadMunicipalities
-- Carga de datos fijos: municipios de la Comunitat Valenciana (provincias 03, 12 y 46), 542 en total.
-- Fuente: INE, «Relación de municipios y códigos a 1 de enero de 2026»
-- (https://www.ine.es/daco/daco42/codmun/26codmun.xlsx). Código = provincia (2) + municipio (3), sin dígito de control.
-- Para actualizar la lista, añadir una migración nueva; no editar esta.
INSERT INTO "municipalities" ("code", "name", "province") VALUES
  ('03002', 'Agost', 'Alicante/Alacant'),
  ('03003', 'Agres', 'Alicante/Alacant'),
  ('03004', 'Aigües', 'Alicante/Alacant'),
  ('03014', 'Alacant/Alicante', 'Alicante/Alacant'),
  ('03005', 'Albatera', 'Alicante/Alacant'),
  ('03006', 'Alcalalí', 'Alicante/Alacant'),
  ('03009', 'Alcoi/Alcoy', 'Alicante/Alacant'),
  ('03008', 'Alcoleja', 'Alicante/Alacant'),
  ('03007', 'Alcosser', 'Alicante/Alacant'),
  ('03010', 'Alfafara', 'Alicante/Alacant'),
  ('03011', 'Alfàs del Pi, l''', 'Alicante/Alacant'),
  ('03012', 'Algorfa', 'Alicante/Alacant'),
  ('03013', 'Algueña', 'Alicante/Alacant'),
  ('03015', 'Almoradí', 'Alicante/Alacant'),
  ('03016', 'Almudaina', 'Alicante/Alacant'),
  ('03017', 'Alqueria d''Asnar, l''', 'Alicante/Alacant'),
  ('03018', 'Altea', 'Alicante/Alacant'),
  ('03019', 'Aspe', 'Alicante/Alacant'),
  ('03001', 'Atzúbia, l''', 'Alicante/Alacant'),
  ('03020', 'Balones', 'Alicante/Alacant'),
  ('03021', 'Banyeres de Mariola', 'Alicante/Alacant'),
  ('03022', 'Benasau', 'Alicante/Alacant'),
  ('03023', 'Beneixama', 'Alicante/Alacant'),
  ('03024', 'Benejúzar', 'Alicante/Alacant'),
  ('03025', 'Benferri', 'Alicante/Alacant'),
  ('03026', 'Beniarbeig', 'Alicante/Alacant'),
  ('03027', 'Beniardà', 'Alicante/Alacant'),
  ('03028', 'Beniarrés', 'Alicante/Alacant'),
  ('03030', 'Benidoleig', 'Alicante/Alacant'),
  ('03031', 'Benidorm', 'Alicante/Alacant'),
  ('03032', 'Benifallim', 'Alicante/Alacant'),
  ('03033', 'Benifato', 'Alicante/Alacant'),
  ('03029', 'Benigembla', 'Alicante/Alacant'),
  ('03034', 'Benijófar', 'Alicante/Alacant'),
  ('03035', 'Benilloba', 'Alicante/Alacant'),
  ('03036', 'Benillup', 'Alicante/Alacant'),
  ('03037', 'Benimantell', 'Alicante/Alacant'),
  ('03038', 'Benimarfull', 'Alicante/Alacant'),
  ('03039', 'Benimassot', 'Alicante/Alacant'),
  ('03040', 'Benimeli', 'Alicante/Alacant'),
  ('03041', 'Benissa', 'Alicante/Alacant'),
  ('03043', 'Biar', 'Alicante/Alacant'),
  ('03044', 'Bigastro', 'Alicante/Alacant'),
  ('03045', 'Bolulla', 'Alicante/Alacant'),
  ('03046', 'Busot', 'Alicante/Alacant'),
  ('03049', 'Callosa de Segura', 'Alicante/Alacant'),
  ('03048', 'Callosa d''en Sarrià', 'Alicante/Alacant'),
  ('03047', 'Calp', 'Alicante/Alacant'),
  ('03051', 'Camp de Mirra, el/Campo de Mirra', 'Alicante/Alacant'),
  ('03050', 'Campello, el', 'Alicante/Alacant'),
  ('03052', 'Cañada', 'Alicante/Alacant'),
  ('03053', 'Castalla', 'Alicante/Alacant'),
  ('03054', 'Castell de Castells', 'Alicante/Alacant'),
  ('03075', 'Castell de Guadalest, el', 'Alicante/Alacant'),
  ('03055', 'Catral', 'Alicante/Alacant'),
  ('03056', 'Cocentaina', 'Alicante/Alacant'),
  ('03057', 'Confrides', 'Alicante/Alacant'),
  ('03058', 'Cox', 'Alicante/Alacant'),
  ('03059', 'Crevillent', 'Alicante/Alacant'),
  ('03061', 'Daya Nueva', 'Alicante/Alacant'),
  ('03062', 'Daya Vieja', 'Alicante/Alacant'),
  ('03063', 'Dénia', 'Alicante/Alacant'),
  ('03064', 'Dolores', 'Alicante/Alacant'),
  ('03066', 'Elda', 'Alicante/Alacant'),
  ('03065', 'Elx/Elche', 'Alicante/Alacant'),
  ('03067', 'Fageca', 'Alicante/Alacant'),
  ('03068', 'Famorca', 'Alicante/Alacant'),
  ('03069', 'Finestrat', 'Alicante/Alacant'),
  ('03077', 'Fondó de les Neus, el/Hondón de las Nieves', 'Alicante/Alacant'),
  ('03070', 'Formentera del Segura', 'Alicante/Alacant'),
  ('03072', 'Gaianes', 'Alicante/Alacant'),
  ('03071', 'Gata de Gorgos', 'Alicante/Alacant'),
  ('03073', 'Gorga', 'Alicante/Alacant'),
  ('03074', 'Granja de Rocamora', 'Alicante/Alacant'),
  ('03076', 'Guardamar del Segura', 'Alicante/Alacant'),
  ('03078', 'Hondón de los Frailes', 'Alicante/Alacant'),
  ('03079', 'Ibi', 'Alicante/Alacant'),
  ('03080', 'Jacarilla', 'Alicante/Alacant'),
  ('03085', 'Llíber', 'Alicante/Alacant'),
  ('03086', 'Millena', 'Alicante/Alacant'),
  ('03088', 'Monforte del Cid', 'Alicante/Alacant'),
  ('03089', 'Monòver/Monóvar', 'Alicante/Alacant'),
  ('03903', 'Montesinos, Los', 'Alicante/Alacant'),
  ('03091', 'Murla', 'Alicante/Alacant'),
  ('03092', 'Muro de Alcoy', 'Alicante/Alacant'),
  ('03090', 'Mutxamel', 'Alicante/Alacant'),
  ('03093', 'Novelda', 'Alicante/Alacant'),
  ('03094', 'Nucia, la', 'Alicante/Alacant'),
  ('03095', 'Ondara', 'Alicante/Alacant'),
  ('03096', 'Onil', 'Alicante/Alacant'),
  ('03097', 'Orba', 'Alicante/Alacant'),
  ('03099', 'Orihuela', 'Alicante/Alacant'),
  ('03084', 'Orxa, l''/Lorcha', 'Alicante/Alacant'),
  ('03098', 'Orxeta', 'Alicante/Alacant'),
  ('03100', 'Parcent', 'Alicante/Alacant'),
  ('03101', 'Pedreguer', 'Alicante/Alacant'),
  ('03102', 'Pego', 'Alicante/Alacant'),
  ('03103', 'Penàguila', 'Alicante/Alacant'),
  ('03104', 'Petrer', 'Alicante/Alacant'),
  ('03902', 'Pilar de la Horadada', 'Alicante/Alacant'),
  ('03105', 'Pinós, el/Pinoso', 'Alicante/Alacant'),
  ('03106', 'Planes', 'Alicante/Alacant'),
  ('03042', 'Poble Nou de Benitatxell, el/Benitachell', 'Alicante/Alacant'),
  ('03901', 'Poblets, els', 'Alicante/Alacant'),
  ('03107', 'Polop', 'Alicante/Alacant'),
  ('03060', 'Quatretondeta', 'Alicante/Alacant'),
  ('03109', 'Rafal', 'Alicante/Alacant'),
  ('03110', 'Ràfol d''Almúnia, el', 'Alicante/Alacant'),
  ('03111', 'Redován', 'Alicante/Alacant'),
  ('03112', 'Relleu', 'Alicante/Alacant'),
  ('03113', 'Rojales', 'Alicante/Alacant'),
  ('03114', 'Romana, la', 'Alicante/Alacant'),
  ('03115', 'Sagra', 'Alicante/Alacant'),
  ('03116', 'Salinas', 'Alicante/Alacant'),
  ('03118', 'San Fulgencio', 'Alicante/Alacant'),
  ('03904', 'San Isidro', 'Alicante/Alacant'),
  ('03120', 'San Miguel de Salinas', 'Alicante/Alacant'),
  ('03117', 'Sanet y Negrals', 'Alicante/Alacant'),
  ('03119', 'Sant Joan d''Alacant', 'Alicante/Alacant'),
  ('03122', 'Sant Vicent del Raspeig/San Vicente del Raspeig', 'Alicante/Alacant'),
  ('03121', 'Santa Pola', 'Alicante/Alacant'),
  ('03123', 'Sax', 'Alicante/Alacant'),
  ('03124', 'Sella', 'Alicante/Alacant'),
  ('03125', 'Senija', 'Alicante/Alacant'),
  ('03127', 'Tàrbena', 'Alicante/Alacant'),
  ('03128', 'Teulada', 'Alicante/Alacant'),
  ('03129', 'Tibi', 'Alicante/Alacant'),
  ('03130', 'Tollos', 'Alicante/Alacant'),
  ('03131', 'Tormos', 'Alicante/Alacant'),
  ('03132', 'Torre de les Maçanes, la/Torremanzanas', 'Alicante/Alacant'),
  ('03133', 'Torrevieja', 'Alicante/Alacant'),
  ('03134', 'Vall d''Alcalà, la', 'Alicante/Alacant'),
  ('03136', 'Vall de Gallinera, la', 'Alicante/Alacant'),
  ('03137', 'Vall de Laguar, la', 'Alicante/Alacant'),
  ('03135', 'Vall d''Ebo, la', 'Alicante/Alacant'),
  ('03138', 'Verger, el', 'Alicante/Alacant'),
  ('03139', 'Vila Joiosa, la/Villajoyosa', 'Alicante/Alacant'),
  ('03140', 'Villena', 'Alicante/Alacant'),
  ('03082', 'Xàbia/Jávea', 'Alicante/Alacant'),
  ('03081', 'Xaló', 'Alicante/Alacant'),
  ('03083', 'Xixona/Jijona', 'Alicante/Alacant'),
  ('12002', 'Aín', 'Castellón/Castelló'),
  ('12003', 'Albocàsser', 'Castellón/Castelló'),
  ('12004', 'Alcalà de Xivert', 'Castellón/Castelló'),
  ('12005', 'Alcora, l''', 'Castellón/Castelló'),
  ('12006', 'Alcudia de Veo', 'Castellón/Castelló'),
  ('12007', 'Alfondeguilla', 'Castellón/Castelló'),
  ('12008', 'Algimia de Almonacid', 'Castellón/Castelló'),
  ('12009', 'Almassora', 'Castellón/Castelló'),
  ('12010', 'Almedíjar', 'Castellón/Castelló'),
  ('12011', 'Almenara', 'Castellón/Castelló'),
  ('12901', 'Alqueries, les/Alquerías del Niño Perdido', 'Castellón/Castelló'),
  ('12012', 'Altura', 'Castellón/Castelló'),
  ('12013', 'Arañuel', 'Castellón/Castelló'),
  ('12014', 'Ares del Maestrat', 'Castellón/Castelló'),
  ('12015', 'Argelita', 'Castellón/Castelló'),
  ('12016', 'Artana', 'Castellón/Castelló'),
  ('12001', 'Atzeneta del Maestrat', 'Castellón/Castelló'),
  ('12017', 'Ayódar', 'Castellón/Castelló'),
  ('12018', 'Azuébar', 'Castellón/Castelló'),
  ('12020', 'Barracas', 'Castellón/Castelló'),
  ('12022', 'Bejís', 'Castellón/Castelló'),
  ('12024', 'Benafer', 'Castellón/Castelló'),
  ('12025', 'Benafigos', 'Castellón/Castelló'),
  ('12026', 'Benassal', 'Castellón/Castelló'),
  ('12027', 'Benicarló', 'Castellón/Castelló'),
  ('12028', 'Benicàssim/Benicasim', 'Castellón/Castelló'),
  ('12029', 'Benlloc', 'Castellón/Castelló'),
  ('12021', 'Betxí', 'Castellón/Castelló'),
  ('12032', 'Borriana/Burriana', 'Castellón/Castelló'),
  ('12031', 'Borriol', 'Castellón/Castelló'),
  ('12033', 'Cabanes', 'Castellón/Castelló'),
  ('12034', 'Càlig', 'Castellón/Castelló'),
  ('12036', 'Canet lo Roig', 'Castellón/Castelló'),
  ('12037', 'Castell de Cabres', 'Castellón/Castelló'),
  ('12038', 'Castellfort', 'Castellón/Castelló'),
  ('12039', 'Castellnovo', 'Castellón/Castelló'),
  ('12040', 'Castelló de la Plana/Castellón de la Plana', 'Castellón/Castelló'),
  ('12041', 'Castillo de Villamalefa', 'Castellón/Castelló'),
  ('12042', 'Catí', 'Castellón/Castelló'),
  ('12043', 'Caudiel', 'Castellón/Castelló'),
  ('12044', 'Cervera del Maestre', 'Castellón/Castelló'),
  ('12053', 'Chilches/Xilxes', 'Castellón/Castelló'),
  ('12056', 'Chóvar', 'Castellón/Castelló'),
  ('12045', 'Cinctorres', 'Castellón/Castelló'),
  ('12046', 'Cirat', 'Castellón/Castelló'),
  ('12048', 'Cortes de Arenoso', 'Castellón/Castelló'),
  ('12049', 'Costur', 'Castellón/Castelló'),
  ('12050', 'Coves de Vinromà, les', 'Castellón/Castelló'),
  ('12051', 'Culla', 'Castellón/Castelló'),
  ('12057', 'Eslida', 'Castellón/Castelló'),
  ('12058', 'Espadilla', 'Castellón/Castelló'),
  ('12059', 'Fanzara', 'Castellón/Castelló'),
  ('12060', 'Figueroles', 'Castellón/Castelló'),
  ('12061', 'Forcall', 'Castellón/Castelló'),
  ('12063', 'Fuente la Reina', 'Castellón/Castelló'),
  ('12064', 'Fuentes de Ayódar', 'Castellón/Castelló'),
  ('12065', 'Gaibiel', 'Castellón/Castelló'),
  ('12067', 'Geldo', 'Castellón/Castelló'),
  ('12068', 'Herbers', 'Castellón/Castelló'),
  ('12069', 'Higueras', 'Castellón/Castelló'),
  ('12070', 'Jana, la', 'Castellón/Castelló'),
  ('12071', 'Jérica', 'Castellón/Castelló'),
  ('12074', 'Llosa, la', 'Castellón/Castelló'),
  ('12072', 'Llucena/Lucena del Cid', 'Castellón/Castelló'),
  ('12073', 'Ludiente', 'Castellón/Castelló'),
  ('12075', 'Mata de Morella, la', 'Castellón/Castelló'),
  ('12076', 'Matet', 'Castellón/Castelló'),
  ('12077', 'Moncofa', 'Castellón/Castelló'),
  ('12078', 'Montán', 'Castellón/Castelló'),
  ('12079', 'Montanejos', 'Castellón/Castelló'),
  ('12080', 'Morella', 'Castellón/Castelló'),
  ('12081', 'Navajas', 'Castellón/Castelló'),
  ('12082', 'Nules', 'Castellón/Castelló'),
  ('12083', 'Olocau del Rey', 'Castellón/Castelló'),
  ('12084', 'Onda', 'Castellón/Castelló'),
  ('12085', 'Orpesa/Oropesa del Mar', 'Castellón/Castelló'),
  ('12087', 'Palanques', 'Castellón/Castelló'),
  ('12088', 'Pavías', 'Castellón/Castelló'),
  ('12089', 'Peníscola/Peñíscola', 'Castellón/Castelló'),
  ('12090', 'Pina de Montalgrao', 'Castellón/Castelló'),
  ('12093', 'Pobla de Benifassà, la', 'Castellón/Castelló'),
  ('12094', 'Pobla Tornesa, la', 'Castellón/Castelló'),
  ('12091', 'Portell de Morella', 'Castellón/Castelló'),
  ('12092', 'Puebla de Arenoso', 'Castellón/Castelló'),
  ('12095', 'Ribesalbes', 'Castellón/Castelló'),
  ('12096', 'Rossell', 'Castellón/Castelló'),
  ('12097', 'Sacañet', 'Castellón/Castelló'),
  ('12098', 'Salzadella, la', 'Castellón/Castelló'),
  ('12101', 'San Rafael del Río', 'Castellón/Castelló'),
  ('12902', 'Sant Joan de Moró', 'Castellón/Castelló'),
  ('12099', 'Sant Jordi/San Jorge', 'Castellón/Castelló'),
  ('12100', 'Sant Mateu', 'Castellón/Castelló'),
  ('12102', 'Santa Magdalena de Pulpis', 'Castellón/Castelló'),
  ('12104', 'Segorbe', 'Castellón/Castelló'),
  ('12103', 'Serratella, la', 'Castellón/Castelló'),
  ('12105', 'Sierra Engarcerán', 'Castellón/Castelló'),
  ('12106', 'Soneja', 'Castellón/Castelló'),
  ('12107', 'Sot de Ferrer', 'Castellón/Castelló'),
  ('12108', 'Suera/Sueras', 'Castellón/Castelló'),
  ('12109', 'Tales', 'Castellón/Castelló'),
  ('12110', 'Teresa', 'Castellón/Castelló'),
  ('12111', 'Tírig', 'Castellón/Castelló'),
  ('12112', 'Todolella', 'Castellón/Castelló'),
  ('12113', 'Toga', 'Castellón/Castelló'),
  ('12114', 'Torás', 'Castellón/Castelló'),
  ('12115', 'Toro, El', 'Castellón/Castelló'),
  ('12116', 'Torralba del Pinar', 'Castellón/Castelló'),
  ('12119', 'Torre d''en Besora, la', 'Castellón/Castelló'),
  ('12120', 'Torre d''en Doménec, la', 'Castellón/Castelló'),
  ('12117', 'Torreblanca', 'Castellón/Castelló'),
  ('12118', 'Torrechiva', 'Castellón/Castelló'),
  ('12121', 'Traiguera', 'Castellón/Castelló'),
  ('12122', 'Useres, les/Useras', 'Castellón/Castelló'),
  ('12124', 'Vall d''Alba', 'Castellón/Castelló'),
  ('12125', 'Vall de Almonacid', 'Castellón/Castelló'),
  ('12126', 'Vall d''Uixó, la', 'Castellón/Castelló'),
  ('12123', 'Vallat', 'Castellón/Castelló'),
  ('12127', 'Vallibona', 'Castellón/Castelló'),
  ('12128', 'Vilafamés', 'Castellón/Castelló'),
  ('12129', 'Vilafranca/Villafranca del Cid', 'Castellón/Castelló'),
  ('12132', 'Vilanova d''Alcolea', 'Castellón/Castelló'),
  ('12134', 'Vilar de Canes', 'Castellón/Castelló'),
  ('12135', 'Vila-real', 'Castellón/Castelló'),
  ('12136', 'Vilavella, la', 'Castellón/Castelló'),
  ('12130', 'Villahermosa del Río', 'Castellón/Castelló'),
  ('12131', 'Villamalur', 'Castellón/Castelló'),
  ('12133', 'Villanueva de Viver', 'Castellón/Castelló'),
  ('12137', 'Villores', 'Castellón/Castelló'),
  ('12138', 'Vinaròs', 'Castellón/Castelló'),
  ('12139', 'Vistabella del Maestrat', 'Castellón/Castelló'),
  ('12140', 'Viver', 'Castellón/Castelló'),
  ('12052', 'Xert', 'Castellón/Castelló'),
  ('12055', 'Xodos/Chodos', 'Castellón/Castelló'),
  ('12141', 'Zorita del Maestrazgo', 'Castellón/Castelló'),
  ('12142', 'Zucaina', 'Castellón/Castelló'),
  ('46001', 'Ademuz', 'Valencia/València'),
  ('46002', 'Ador', 'Valencia/València'),
  ('46004', 'Agullent', 'Valencia/València'),
  ('46042', 'Aielo de Malferit', 'Valencia/València'),
  ('46043', 'Aielo de Rugat', 'Valencia/València'),
  ('46005', 'Alaquàs', 'Valencia/València'),
  ('46006', 'Albaida', 'Valencia/València'),
  ('46007', 'Albal', 'Valencia/València'),
  ('46008', 'Albalat de la Ribera', 'Valencia/València'),
  ('46009', 'Albalat dels Sorells', 'Valencia/València'),
  ('46010', 'Albalat dels Tarongers', 'Valencia/València'),
  ('46011', 'Alberic', 'Valencia/València'),
  ('46012', 'Alborache', 'Valencia/València'),
  ('46013', 'Alboraia/Alboraya', 'Valencia/València'),
  ('46014', 'Albuixech', 'Valencia/València'),
  ('46016', 'Alcàntera de Xúquer', 'Valencia/València'),
  ('46015', 'Alcàsser', 'Valencia/València'),
  ('46018', 'Alcublas', 'Valencia/València'),
  ('46020', 'Alcúdia de Crespins, l''', 'Valencia/València'),
  ('46019', 'Alcúdia, l''', 'Valencia/València'),
  ('46021', 'Aldaia', 'Valencia/València'),
  ('46022', 'Alfafar', 'Valencia/València'),
  ('46024', 'Alfara de la Baronia', 'Valencia/València'),
  ('46025', 'Alfara del Patriarca', 'Valencia/València'),
  ('46026', 'Alfarb', 'Valencia/València'),
  ('46027', 'Alfarrasí', 'Valencia/València'),
  ('46023', 'Alfauir', 'Valencia/València'),
  ('46028', 'Algar de Palància', 'Valencia/València'),
  ('46029', 'Algemesí', 'Valencia/València'),
  ('46030', 'Algímia d''Alfara', 'Valencia/València'),
  ('46031', 'Alginet', 'Valencia/València'),
  ('46032', 'Almàssera', 'Valencia/València'),
  ('46033', 'Almiserà', 'Valencia/València'),
  ('46034', 'Almoines', 'Valencia/València'),
  ('46035', 'Almussafes', 'Valencia/València'),
  ('46036', 'Alpuente', 'Valencia/València'),
  ('46037', 'Alqueria de la Comtessa, l''', 'Valencia/València'),
  ('46017', 'Alzira', 'Valencia/València'),
  ('46038', 'Andilla', 'Valencia/València'),
  ('46039', 'Anna', 'Valencia/València'),
  ('46040', 'Antella', 'Valencia/València'),
  ('46041', 'Aras de los Olmos', 'Valencia/València'),
  ('46003', 'Atzeneta d''Albaida', 'Valencia/València'),
  ('46044', 'Ayora', 'Valencia/València'),
  ('46046', 'Barx', 'Valencia/València'),
  ('46045', 'Barxeta', 'Valencia/València'),
  ('46047', 'Bèlgida', 'Valencia/València'),
  ('46048', 'Bellreguard', 'Valencia/València'),
  ('46049', 'Bellús', 'Valencia/València'),
  ('46050', 'Benagéber', 'Valencia/València'),
  ('46051', 'Benaguasil', 'Valencia/València'),
  ('46052', 'Benavites', 'Valencia/València'),
  ('46053', 'Beneixida', 'Valencia/València'),
  ('46054', 'Benetússer', 'Valencia/València'),
  ('46055', 'Beniarjó', 'Valencia/València'),
  ('46056', 'Beniatjar', 'Valencia/València'),
  ('46057', 'Benicolet', 'Valencia/València'),
  ('46904', 'Benicull de Xúquer', 'Valencia/València'),
  ('46060', 'Benifaió', 'Valencia/València'),
  ('46059', 'Benifairó de la Valldigna', 'Valencia/València'),
  ('46058', 'Benifairó de les Valls', 'Valencia/València'),
  ('46061', 'Beniflá', 'Valencia/València'),
  ('46062', 'Benigànim', 'Valencia/València'),
  ('46063', 'Benimodo', 'Valencia/València'),
  ('46064', 'Benimuslem', 'Valencia/València'),
  ('46065', 'Beniparrell', 'Valencia/València'),
  ('46066', 'Benirredrà', 'Valencia/València'),
  ('46067', 'Benissanó', 'Valencia/València'),
  ('46068', 'Benissoda', 'Valencia/València'),
  ('46069', 'Benissuera', 'Valencia/València'),
  ('46070', 'Bétera', 'Valencia/València'),
  ('46071', 'Bicorp', 'Valencia/València'),
  ('46072', 'Bocairent', 'Valencia/València'),
  ('46073', 'Bolbaite', 'Valencia/València'),
  ('46074', 'Bonrepòs i Mirambell', 'Valencia/València'),
  ('46075', 'Bufali', 'Valencia/València'),
  ('46076', 'Bugarra', 'Valencia/València'),
  ('46077', 'Buñol', 'Valencia/València'),
  ('46078', 'Burjassot', 'Valencia/València'),
  ('46079', 'Calles', 'Valencia/València'),
  ('46080', 'Camporrobles', 'Valencia/València'),
  ('46081', 'Canals', 'Valencia/València'),
  ('46082', 'Canet d''En Berenguer', 'Valencia/València'),
  ('46083', 'Carcaixent', 'Valencia/València'),
  ('46084', 'Càrcer', 'Valencia/València'),
  ('46085', 'Carlet', 'Valencia/València'),
  ('46086', 'Carrícola', 'Valencia/València'),
  ('46087', 'Casas Altas', 'Valencia/València'),
  ('46088', 'Casas Bajas', 'Valencia/València'),
  ('46089', 'Casinos', 'Valencia/València'),
  ('46257', 'Castelló', 'Valencia/València'),
  ('46090', 'Castelló de Rugat', 'Valencia/València'),
  ('46091', 'Castellonet de la Conquesta', 'Valencia/València'),
  ('46092', 'Castielfabib', 'Valencia/València'),
  ('46093', 'Catadau', 'Valencia/València'),
  ('46094', 'Catarroja', 'Valencia/València'),
  ('46095', 'Caudete de las Fuentes', 'Valencia/València'),
  ('46096', 'Cerdà', 'Valencia/València'),
  ('46107', 'Chella', 'Valencia/València'),
  ('46106', 'Chelva', 'Valencia/València'),
  ('46108', 'Chera', 'Valencia/València'),
  ('46109', 'Cheste', 'Valencia/València'),
  ('46111', 'Chiva', 'Valencia/València'),
  ('46112', 'Chulilla', 'Valencia/València'),
  ('46097', 'Cofrentes', 'Valencia/València'),
  ('46098', 'Corbera', 'Valencia/València'),
  ('46099', 'Cortes de Pallás', 'Valencia/València'),
  ('46100', 'Cotes', 'Valencia/València'),
  ('46105', 'Cullera', 'Valencia/València'),
  ('46113', 'Daimús', 'Valencia/València'),
  ('46114', 'Domeño', 'Valencia/València'),
  ('46115', 'Dos Aguas', 'Valencia/València'),
  ('46116', 'Eliana, l''', 'Valencia/València'),
  ('46117', 'Emperador', 'Valencia/València'),
  ('46118', 'Enguera', 'Valencia/València'),
  ('46119', 'Énova, l''', 'Valencia/València'),
  ('46120', 'Estivella', 'Valencia/València'),
  ('46121', 'Estubeny', 'Valencia/València'),
  ('46122', 'Faura', 'Valencia/València'),
  ('46123', 'Favara', 'Valencia/València'),
  ('46126', 'Foios', 'Valencia/València'),
  ('46128', 'Font de la Figuera, la', 'Valencia/València'),
  ('46127', 'Font d''en Carròs, la', 'Valencia/València'),
  ('46124', 'Fontanars dels Alforins', 'Valencia/València'),
  ('46125', 'Fortaleny', 'Valencia/València'),
  ('46129', 'Fuenterrobles', 'Valencia/València'),
  ('46131', 'Gandia', 'Valencia/València'),
  ('46902', 'Gátova', 'Valencia/València'),
  ('46130', 'Gavarda', 'Valencia/València'),
  ('46132', 'Genovés, el', 'Valencia/València'),
  ('46133', 'Gestalgar', 'Valencia/València'),
  ('46134', 'Gilet', 'Valencia/València'),
  ('46135', 'Godella', 'Valencia/València'),
  ('46136', 'Godelleta', 'Valencia/València'),
  ('46137', 'Granja de la Costera, la', 'Valencia/València'),
  ('46138', 'Guadasséquies', 'Valencia/València'),
  ('46139', 'Guadassuar', 'Valencia/València'),
  ('46140', 'Guardamar de la Safor', 'Valencia/València'),
  ('46141', 'Higueruelas', 'Valencia/València'),
  ('46142', 'Jalance', 'Valencia/València'),
  ('46144', 'Jarafuel', 'Valencia/València'),
  ('46154', 'Llanera de Ranes', 'Valencia/València'),
  ('46155', 'Llaurí', 'Valencia/València'),
  ('46147', 'Llíria', 'Valencia/València'),
  ('46152', 'Llocnou de la Corona', 'Valencia/València'),
  ('46153', 'Llocnou de Sant Jeroni', 'Valencia/València'),
  ('46151', 'Llocnou d''En Fenollet', 'Valencia/València'),
  ('46156', 'Llombai', 'Valencia/València'),
  ('46157', 'Llosa de Ranes, la', 'Valencia/València'),
  ('46150', 'Llutxent', 'Valencia/València'),
  ('46148', 'Loriguilla', 'Valencia/València'),
  ('46149', 'Losa del Obispo', 'Valencia/València'),
  ('46158', 'Macastre', 'Valencia/València'),
  ('46159', 'Manises', 'Valencia/València'),
  ('46160', 'Manuel', 'Valencia/València'),
  ('46161', 'Marines', 'Valencia/València'),
  ('46162', 'Massalavés', 'Valencia/València'),
  ('46163', 'Massalfassar', 'Valencia/València'),
  ('46164', 'Massamagrell', 'Valencia/València'),
  ('46165', 'Massanassa', 'Valencia/València'),
  ('46166', 'Meliana', 'Valencia/València'),
  ('46167', 'Millares', 'Valencia/València'),
  ('46168', 'Miramar', 'Valencia/València'),
  ('46169', 'Mislata', 'Valencia/València'),
  ('46170', 'Moixent/Mogente', 'Valencia/València'),
  ('46171', 'Montcada/Moncada', 'Valencia/València'),
  ('46173', 'Montaverner', 'Valencia/València'),
  ('46174', 'Montesa', 'Valencia/València'),
  ('46175', 'Montitxelvo/Montichelvo', 'Valencia/València'),
  ('46176', 'Montroi/Montroy', 'Valencia/València'),
  ('46172', 'Montserrat', 'Valencia/València'),
  ('46177', 'Museros', 'Valencia/València'),
  ('46178', 'Nàquera/Náquera', 'Valencia/València'),
  ('46179', 'Navarrés', 'Valencia/València'),
  ('46180', 'Novetlè', 'Valencia/València'),
  ('46181', 'Oliva', 'Valencia/València'),
  ('46183', 'Olleria, l''', 'Valencia/València'),
  ('46182', 'Olocau', 'Valencia/València'),
  ('46184', 'Ontinyent', 'Valencia/València'),
  ('46185', 'Otos', 'Valencia/València'),
  ('46186', 'Paiporta', 'Valencia/València'),
  ('46187', 'Palma de Gandía', 'Valencia/València'),
  ('46188', 'Palmera', 'Valencia/València'),
  ('46189', 'Palomar, el', 'Valencia/València'),
  ('46190', 'Paterna', 'Valencia/València'),
  ('46191', 'Pedralba', 'Valencia/València'),
  ('46192', 'Petrés', 'Valencia/València'),
  ('46193', 'Picanya', 'Valencia/València'),
  ('46194', 'Picassent', 'Valencia/València'),
  ('46195', 'Piles', 'Valencia/València'),
  ('46196', 'Pinet', 'Valencia/València'),
  ('46199', 'Pobla de Farnals, la', 'Valencia/València'),
  ('46202', 'Pobla de Vallbona, la', 'Valencia/València'),
  ('46200', 'Pobla del Duc, la', 'Valencia/València'),
  ('46203', 'Pobla Llarga, la', 'Valencia/València'),
  ('46197', 'Polinyà de Xúquer', 'Valencia/València'),
  ('46198', 'Potries', 'Valencia/València'),
  ('46205', 'Puçol', 'Valencia/València'),
  ('46201', 'Puebla de San Miguel', 'Valencia/València'),
  ('46204', 'Puig de Santa Maria, el', 'Valencia/València'),
  ('46101', 'Quart de les Valls', 'Valencia/València'),
  ('46102', 'Quart de Poblet', 'Valencia/València'),
  ('46103', 'Quartell', 'Valencia/València'),
  ('46104', 'Quatretonda', 'Valencia/València'),
  ('46206', 'Quesa', 'Valencia/València'),
  ('46207', 'Rafelbunyol', 'Valencia/València'),
  ('46208', 'Rafelcofer', 'Valencia/València'),
  ('46209', 'Rafelguaraf', 'Valencia/València'),
  ('46210', 'Ráfol de Salem', 'Valencia/València'),
  ('46212', 'Real', 'Valencia/València'),
  ('46211', 'Real de Gandia, el', 'Valencia/València'),
  ('46213', 'Requena', 'Valencia/València'),
  ('46214', 'Riba-roja de Túria', 'Valencia/València'),
  ('46215', 'Riola', 'Valencia/València'),
  ('46216', 'Rocafort', 'Valencia/València'),
  ('46217', 'Rotglà i Corberà', 'Valencia/València'),
  ('46218', 'Ròtova', 'Valencia/València'),
  ('46219', 'Rugat', 'Valencia/València'),
  ('46220', 'Sagunt/Sagunto', 'Valencia/València'),
  ('46221', 'Salem', 'Valencia/València'),
  ('46903', 'San Antonio de Benagéber', 'Valencia/València'),
  ('46222', 'Sant Joanet', 'Valencia/València'),
  ('46223', 'Sedaví', 'Valencia/València'),
  ('46224', 'Segart', 'Valencia/València'),
  ('46225', 'Sellent', 'Valencia/València'),
  ('46226', 'Sempere', 'Valencia/València'),
  ('46227', 'Senyera', 'Valencia/València'),
  ('46228', 'Serra', 'Valencia/València'),
  ('46229', 'Siete Aguas', 'Valencia/València'),
  ('46230', 'Silla', 'Valencia/València'),
  ('46231', 'Simat de la Valldigna', 'Valencia/València'),
  ('46232', 'Sinarcas', 'Valencia/València'),
  ('46233', 'Sollana', 'Valencia/València'),
  ('46234', 'Sot de Chera', 'Valencia/València'),
  ('46235', 'Sueca', 'Valencia/València'),
  ('46236', 'Sumacàrcer', 'Valencia/València'),
  ('46237', 'Tavernes Blanques', 'Valencia/València'),
  ('46238', 'Tavernes de la Valldigna', 'Valencia/València'),
  ('46239', 'Teresa de Cofrentes', 'Valencia/València'),
  ('46240', 'Terrateig', 'Valencia/València'),
  ('46241', 'Titaguas', 'Valencia/València'),
  ('46242', 'Torrebaja', 'Valencia/València'),
  ('46243', 'Torrella', 'Valencia/València'),
  ('46244', 'Torrent', 'Valencia/València'),
  ('46245', 'Torres Torres', 'Valencia/València'),
  ('46246', 'Tous', 'Valencia/València'),
  ('46247', 'Tuéjar', 'Valencia/València'),
  ('46248', 'Turís', 'Valencia/València'),
  ('46249', 'Utiel', 'Valencia/València'),
  ('46250', 'València', 'Valencia/València'),
  ('46251', 'Vallada', 'Valencia/València'),
  ('46252', 'Vallanca', 'Valencia/València'),
  ('46253', 'Vallés', 'Valencia/València'),
  ('46254', 'Venta del Moro', 'Valencia/València'),
  ('46255', 'Vilallonga/Villalonga', 'Valencia/València'),
  ('46256', 'Vilamarxant', 'Valencia/València'),
  ('46258', 'Villar del Arzobispo', 'Valencia/València'),
  ('46259', 'Villargordo del Cabriel', 'Valencia/València'),
  ('46260', 'Vinalesa', 'Valencia/València'),
  ('46145', 'Xàtiva', 'Valencia/València'),
  ('46143', 'Xeraco', 'Valencia/València'),
  ('46146', 'Xeresa', 'Valencia/València'),
  ('46110', 'Xirivella', 'Valencia/València'),
  ('46261', 'Yátova', 'Valencia/València'),
  ('46262', 'Yesa, La', 'Valencia/València'),
  ('46263', 'Zarra', 'Valencia/València');
